/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        arduino: '#00979D',
        esp32: '#E7352C',
        // ===== Dynamic design tokens (CSS vars — overridable by tenant) =====
        'deep-navy': 'var(--ds-primary, #102348)',
        'stem-orange': 'var(--ds-secondary, #EA8E0A)',
        'indigo-accent': 'var(--ds-secondary, #6366F1)',
        'pure-white': 'var(--ds-surface-container-lowest, #FFFFFF)',
        'bg-off-white': 'var(--ds-surface, #F5F5F5)',
        primary: 'var(--ds-primary, #000d2b)',
        'primary-container': 'var(--ds-primary-container, #102348)',
        'on-primary': 'var(--ds-on-primary, #ffffff)',
        'primary-fixed': 'var(--ds-primary-fixed, #d9e2ff)',
        'on-primary-fixed-variant': 'var(--ds-on-primary-fixed-variant, #35466d)',
        'on-primary-container': 'var(--ds-on-primary-container, #7a8bb6)',
        secondary: 'var(--ds-secondary, #8a5100)',
        'secondary-container': 'var(--ds-secondary-container, #fd9d22)',
        'secondary-fixed': 'var(--ds-secondary-fixed, #ffdcbd)',
        'secondary-fixed-dim': 'var(--ds-secondary-fixed-dim, #ffb86d)',
        'on-secondary-container': 'var(--ds-on-secondary-container, #673b00)',
        tertiary: 'var(--ds-tertiary, #030047)',
        background: 'var(--ds-background, #f9f9f9)',
        surface: 'var(--ds-surface, #f9f9f9)',
        'surface-variant': 'var(--ds-surface-variant, #e2e2e2)',
        'surface-container-lowest': 'var(--ds-surface-container-lowest, #ffffff)',
        'surface-container-low': 'var(--ds-surface-container-low, #f3f3f3)',
        'surface-container': 'var(--ds-surface-container, #eeeeee)',
        'surface-container-high': 'var(--ds-surface-container-high, #e8e8e8)',
        'surface-container-highest': 'var(--ds-surface-container-highest, #e2e2e2)',
        'surface-bright': 'var(--ds-surface-bright, #f9f9f9)',
        'surface-dim': 'var(--ds-surface-dim, #dadada)',
        'on-surface': 'var(--ds-on-surface, #1a1c1c)',
        'on-surface-variant': 'var(--ds-on-surface-variant, #44464e)',
        'on-background': 'var(--ds-on-background, #1a1c1c)',
        outline: 'var(--ds-outline, #75777f)',
        'outline-variant': 'var(--ds-outline-variant, #c5c6cf)',
        error: 'var(--ds-error, #ba1a1a)',
        'on-error': 'var(--ds-on-error, #ffffff)',
        'error-container': 'var(--ds-error-container, #ffdad6)',
        'on-error-container': 'var(--ds-on-error-container, #93000a)',
      },
      borderRadius: {
        DEFAULT: 'var(--ds-rounded, 0.125rem)',
        lg: 'var(--ds-rounded-lg, 0.25rem)',
        xl: 'var(--ds-rounded-xl, 0.5rem)',
        full: 'var(--ds-rounded-full, 0.75rem)',
      },
      spacing: {
        base: '8px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        gutter: 'var(--ds-gutter, 24px)',
        'margin-mobile': 'var(--ds-margin-mobile, 16px)',
        'margin-desktop': 'var(--ds-margin-desktop, 48px)',
        'container-max': 'var(--ds-container-max, 1280px)',
      },
      maxWidth: {
        'container-max': 'var(--ds-container-max, 1280px)',
      },
      fontFamily: {
        sans: ['var(--ds-font-family)', 'Inter', 'Roboto', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '700' }],
      },
      boxShadow: {
        ambient: '0 4px 20px -2px rgba(16, 35, 72, 0.12)',
      },
    },
  },
  plugins: [],
};
